name: Manual Test Quote-NewPolicy-Resolve flow
on:
  workflow_dispatch:
    inputs:
      api_url:
        description: "Quote API URL"
        required: true
      api_key:
        description: "Quote API KEY"
        required: true
      json_data:
        description: "Quote Json Data"
        required: true
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - env:
          RELAY_API_KEY: ${{ secrets.RELAY_API_KEY }}
          RELAY_API_SECRET: ${{ secrets.RELAY_API_SECRET }}
          # QUOTE_API_URL: ${{ secrets.QUOTE_API_URL }}
          # QUOTE_API_KEY: ${{ secrets.QUOTE_API_KEY }}
          # QUOTE_JSON_DATA: ${{ secrets.QUOTE_JSON_DATA }}
          RM_ADDRESS: ${{ secrets.RM_ADDRESS }}
          CUSTOMER: "0xD758aF6BFC2f0908D7C5f89942be52C36a6b3cab"
        run: |
          export QUOTE_API_KEY=${{ github.event.inputs.api_key }}
          ./cli.js quote-policy ${{ github.event.inputs.api_url }} --payout 5000 --json-data '${{ github.event.inputs.json_data }}' --output-file signed-quote-policy-input.json
          sleep 15
          ./cli.js new-policy signed-quote-policy-input.json $CUSTOMER --output-file signed-quote-policy-output.json
          sleep 15
          ./cli.js resolve-policy signed-quote-policy-output.json 3000
